Repository comindware/core-ui, pull requests merged in 2019-09, with the labels that each got.

#945 ComplexEditor: fix script localization.
  src/form/editors/ComplexEditorView.js
Labels: 2.0

#946 ComplexEditor: fix script localization.
  src/form/editors/ComplexEditorView.js
Labels: 1.13

#947 2.0/toolbar cherry pick
  resources/styles/common.css
  src/components/toolbar/ToolbarView.js
  src/components/toolbar/classes/GroupedCollection.js
Labels: 2.0

#943 [#182690]fix editors
  dist/localization/localization.de.json
  dist/localization/localization.en.json
  dist/localization/localization.ru.json
  localization/localization.deleted.n3
  localization/localization.n3
  localization/localization.ru.n3
  src/form/editors/ComplexEditorView.js
  src/form/editors/impl/codeEditor/templates/toolbar.html
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  src/form/editors/impl/codeEditor/views/ToolbarView.js
Labels: 2.0, need review

#950 Fix dropdown position adjustment, notification overflow(IE)
  resources/styles/dropdown.css
  resources/styles/notifications.css
  src/dropdown/views/DropdownView.js
  src/list/views/header/GridHeaderView.js
Labels: 1.13

#955 Controller: fix setLoading call without context.
  src/controller/Controller.ts
Labels: 2.0

#957 Toolbar: add isRendered check to rebuild.
  src/components/toolbar/ToolbarView.js
Labels: 2.0

#958 Toolbar: add isRendered check to rebuild.
  src/components/toolbar/ToolbarView.js
Labels: 1.13

#960 SplitView: some fixes.
  resources/styles/common.css
  src/Meta.ts
  src/components/toolbar/ToolbarView.js
  src/components/toolbar/views/CustomActionGroupView.js
  src/layout/split/SplitPanel.js
  src/services/UIService.ts
  src/views/SplitPanelResizer.js
  src/views/SplitPanelView.js
Labels: 2.0

#961 CodeEditor: fix bugs setValue and complie
  src/form/editors/CodeEditorView.ts
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.0

#924 [#449438]fix correcte display text, add localizer
  src/list/views/GridView.ts
Labels: 2.0, draft

#967 GridView: add replace columns method (from 1.13).
  src/form/editors/base/MarionetteEditorPrototype.ts
  src/list/views/GridView.ts
Labels: 2.0

#959 Fix pointers in grid header & data in collection
  resources/styles/list.css
  src/list/templates/gridheader.hbs
  src/list/views/header/GridHeaderView.ts
Labels: 2.0, need review

#964 [#455298]Lists:fix state hidden 'eyes'
  src/components/treeEditor/controllers/DiffController.ts
Labels: 2.0, draft, need review

#968 GridView: fix scroll on fullscreen mode, PopupStack: fix remove popup for show $el in popup.
  resources/styles/list.css
  src/views/PopupStackView.js
Labels: 2.0
