Repository comindware/core-ui, pull requests merged in 2019-10, with the labels that each got.

#973 [#455298]TreeEditor: update columns
  src/list/views/GridView.ts
Labels: 2.0, need review

#977 VSCode workspace: add eslint to recommendation, enable for ts, remove annoying properties.
  vc-config.code-workspace
Labels: 2.0

#978 [#458457] Tree Editor: fix apply button display.
  resources/styles/treeEditor.css
Labels: 2.0

#976 fix highlighted check condition
  src/list/behaviors/GridCollapsibleItemBehavior.ts
Labels: 2.0

#979 Fix running test (but skip some)
  karma.conf.js
  src/Application.ts
  src/form/editors/ColorPickerEditor.ts
  src/form/editors/DocumentEditorView.js
  src/form/editors/NumberEditorView.js
  src/form/editors/TextEditorView.js
  src/form/editors/base/MarionetteEditorPrototype.ts
  src/services/LocalizationService.ts
  tests/specs/components/Toolbar.spec.js
  tests/specs/form/DatalistEditorView.spec.js
  tests/specs/form/DateTimeEditorView.spec.js
  tests/specs/form/IconEditorView.spec.js
  tests/specs/form/MemberSplitEditor.spec.js
  tests/specs/form/TextEditorView.spec.js
  tests/specs/grid/Comparators.spec.js
Labels: 2.0

#987 2.0/release
  resources/styles/dropdown.css
  resources/styles/notifications.css
  src/form/editors/ContextSelectEditorView.js
Labels: 2.0

#989 2.0/sprint w40fixes
  resources/styles/common.css
  resources/styles/form.css
  resources/styles/themes/main/index.js
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/templates/panel.hbs
  src/form/editors/impl/datalist/views/PanelView.js
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.0

#993 Datalist: fix document, Collection: focus last cell fixes.
  resources/styles/form.css
  resources/styles/themes/theme.css
  src/form/editors/DatalistEditorView.ts
  src/list/views/CollectionView.ts
  src/list/views/GridView.ts
  src/list/views/RowView.ts
Labels: 2.0

#996 [#458576] Collection: fix ctrl + A for editable cells.
  src/list/views/CollectionView.ts
Labels: 2.0

#988 [#458567]TreeEditor:add methods
  .vscode/settings.json
  src/components/treeEditor/TreeEditor.ts
  src/components/treeEditor/controllers/DiffController.ts
  src/list/views/GridView.ts
Labels: 2.0, needs work

#998 Datalist: reverse selected in dropdown depends open position.
  demo/app/cases/editors/UserEditor.js
  resources/styles/common.css
  resources/styles/dropdown.css
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/templates/panel.hbs
  src/form/editors/impl/datalist/views/PanelView.js
Labels: 2.0

#991 [#489579] GridView:add logick hidden column visibility
  src/list/views/GridView.ts
Labels: 2.0, needs work

#1002 Fix area for closing filter's popup
  src/list/templates/grid.hbs
  src/list/views/GridView.ts
Labels: 2.0

#1006 [#461642] GridView: fix collection search
  src/list/views/GridView.ts
Labels: 2.0

#1004 [#455211] Grid: move cell left/right through key (personalConfig)
  src/list/views/GridView.ts
Labels: 2.0

#1005 [#458548]Fix Split-view button collapse
  src/views/SplitPanelResizer.js
Labels: 2.0

#1009 Fix popup loading
  src/layout/popup/popup.hbs
  tests/specs/components/PopupView.spec.js
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.0

#1010 [#459249] TabLayouts: fix visible
  src/layout/tabLayout/TabLayoutView.ts
Labels: 2.0

#1012 [#462534] DocumentEditor: add preview button (link just download file).
  resources/styles/form.css
  src/Meta.ts
  src/form/editors/DocumentEditorView.js
  src/form/editors/iconsWraps/iconWrapPreview.html
  src/form/editors/impl/document/gallery/AttachmentsController.js
  src/form/editors/impl/document/templates/documentBubbleItem.html
  src/form/editors/impl/document/views/DocumentBubbleItemView.ts
  src/services/UIService.ts
Labels: 2.0

#1014 [#435361] Grid: fix autocomplete.
  src/views/templates/searchBar.hbs
Labels: 2.0

#1016 [#459075] CodeMirror: fix styles application
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.0, needs work

#990 [#459195]CodeEditor: fix position tooltip
  resources/styles/codemirror.css
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.0, needs work

#1017 [#462530] Fix list separator (add hover)
  resources/styles/common.css
Labels: 2.0, need review

#1027 Split View: nowrap for big screens.
  resources/styles/common.css
  src/form/editors/impl/document/meta.ts
Labels: 2.0

#1022 [#462148] Fix layout eye-button on basic form
  resources/styles/treeEditor.css
  src/layout/resources/tabLayout.css
  src/layout/tabLayout/TabLayoutView.ts
  src/layout/tabLayout/templates/tabLayout.hbs
Labels: 2.0, need review

#1030 Boolean editor and grid fixes
  src/form/editors/BooleanEditorView.ts
  src/form/editors/templates/booleanEditor.hbs
  src/form/editors/templates/booleanEditor.html
  src/list/views/CollectionView.ts
  src/list/views/GridView.ts
  src/list/views/RowView.ts
  tests/specs/form/BooleanEditorView.spec.js
Labels: 2.0

#1003 [#460872][#461554][#459390][463085]Fix memberSelect loading (Core UI) + optimized + smallBugFix
  src/form/editors/MembersSplitEditorView.ts
  src/form/editors/impl/membersSplit/controller/MembersSplitController.ts
  src/form/editors/impl/membersSplit/views/AvailableGridView.js
  src/form/editors/impl/membersSplit/views/AvailableGridView.ts
  src/form/editors/impl/membersSplit/views/BaseMembersGridView.js
  src/form/editors/impl/membersSplit/views/BaseMembersGridView.ts
  src/form/editors/impl/membersSplit/views/SelectedGridView.js
  tests/specs/form/MemberSplitEditor.spec.js
Labels: 2.0, needs work
