Repository comindware/core-ui, pull requests merged in 2019-11, with the labels that each got.

#1036 DocumentEditor: fix preview title.
  localization/localization.n3
  localization/localization.ru.n3
  src/form/editors/impl/document/templates/documentBubbleItem.html
  src/form/editors/impl/document/views/DocumentBubbleItemView.ts
Labels: 2.0, Stas review me please

#1033 [#462749] Fix display codemirror editor in complex with initial value.
  src/form/editors/CodeEditorView.ts
Labels: 2.0, Stas review me please

#1035 [#462148] Fix selected tabs
  src/layout/resources/tabLayout.css
Labels: 2.0, Stas review me please

#1031 [#391522] add attribute 'title' for tag <label>
  src/form/editors/base/MarionetteEditorPrototype.ts
Labels: 2.0, Stas review me please

#1032 [#457724] DataTimeButton: fix width
  resources/styles/themes/new/styles.css
Labels: 2.0, Stas review me please

#1041 Fix magic horizobntal scroll in grid
  resources/styles/list.css
Labels: 2.0

#1038 [#456907] DocumentEditor: fix display names docs, button (showAll/Hid…
  resources/styles/form.css
  resources/styles/themes/new/styles.css
  src/form/editors/DocumentEditorView.js
Labels: 2.0

#1042 [#432147] Dropdown: fix dropdown anchor, add IE append polyfill.
  src/components/treeEditor/TreeEditor.ts
  src/dropdown/views/DropdownView.ts
  src/services/IEService.ts
  src/services/UIService.ts
Labels: 2.0, Stas review me please

#1045 RequiredValidator: add context.
  src/form/validators/requiredValidator.ts
  src/utils/underscore.ts
Labels: 2.0, Stas review me please

#1043 Fix radio button margin in filter
  resources/styles/themes/new/index.js
  resources/styles/themes/theme.css
  src/list/templates/filterPanel/configPanelAggregation.html
  src/list/views/сonfigurationPanel/ConfigPanelAggregationView.js
Labels: 2.0, Stas review me please

#1047 [#463902] IE, Edge: insertAdjacent polifills added for SVG.
  src/services/EdgeService.ts
  src/services/IEService.ts
Labels: 2.0, Stas review me please

#1048 [#462941] Datalist: fix readonly height. Boolean: fix readonly bgcolor.
  resources/styles/form.css
  resources/styles/themes/theme.css
  src/services/IEService.ts
Labels: 2.0

#1023 2.0/release
  src/form/editors/impl/codeEditor/Constants.js
  src/form/editors/impl/codeEditor/services/CmwCodeAssistantServices.js
  src/form/editors/impl/codeEditor/services/MappingService.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  src/utils/keyCode.ts
  tests/utils/OntologyService.js
Labels: 2.0, question

#1050 [#463888] Grid: improved width, resize logic for columns.
  resources/styles/list.css
  src/list/views/GridView.ts
  src/list/views/header/GridHeaderView.ts
Labels: 2.0

#1044 [#189143][#463028]Fix split-view on window resize
  resources/styles/common.css
  src/views/SplitPanelResizer.js
  src/views/SplitPanelView.js
Labels: 2.0

#1053 Fix toolbar btn's displaying
  resources/styles/common.css
Labels: 2.0

#1051 [#464072] Datalist: fixed Excess Warning, added tests.
  resources/styles/dropdown.css
  resources/styles/form.css
  src/form/editors/impl/datalist/collections/DemoReferenceCollection.js
  src/form/editors/impl/datalist/templates/panel.hbs
  src/form/editors/impl/datalist/views/PanelView.js
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.0

#1052 DataSet: fix style emptyView
  resources/styles/list.css
Labels: 2.0

#1054 Editors: fixed show errors logic.
  src/form/editors/base/MarionetteEditorPrototype.ts
Labels: 2.0

#1056 [#461935] PersonalConfig: fix width elements on form
  src/components/treeEditor/controllers/DiffController.ts
Labels: 2.0

#1057 [#464618] Fix icon size on preview of picture
  resources/styles/gallery.css
Labels: 2.0, Stas review me please

#1059 Datalist: fixed remove icon position.
  resources/styles/dropdown.css
  resources/styles/themes/theme.css
  src/form/editors/impl/datalist/views/BubbleItemView.ts
Labels: 2.0

#1060 Fix sorting arrows, export errors panel
  demo/package-lock.json
  demo/package.json
  package-lock.json
  package.json
  resources/styles/themes/theme.css
  src/coreApi.ts
  src/form/editors/base/MarionetteEditorPrototype.ts
  src/list/meta.js
  src/list/templates/gridheader.hbs
  src/list/views/GridView.ts
  src/list/views/header/GridHeaderView.ts
  src/views/ErrorsPanelView.js
Labels: 2.0

#1046 [#464965][#464527] Fix checkbox for IE and Edge
  resources/styles/list.css
  resources/styles/themes/theme.css
Labels: 2.0, Stas review me please

#1058 [#459805] Add outline on error cells
  resources/styles/list.css
  resources/styles/themes/theme.css
Labels: 2.0, Stas review me please

#1061 [#462542][#462534] Document: replace review to download, layout fixes.
  resources/styles/gallery.css
  resources/styles/themes/theme.css
  src/form/editors/DocumentEditorView.js
  src/form/editors/iconsWraps/iconWrapDownload.html
  src/form/editors/iconsWraps/iconWrapPreview.html
  src/form/editors/impl/document/gallery/AttachmentsController.js
  src/form/editors/impl/document/gallery/templates/galleryWindow.html
  src/form/editors/impl/document/gallery/views/GalleryWindowView.js
  src/form/editors/impl/document/templates/documentBubbleItem.html
  src/form/editors/impl/document/views/DocumentBubbleItemView.ts
Labels: 2.0, Stas review me please

#1062 [#464965][#464527] Fix checkbox for IE and Edge
  resources/styles/themes/theme.css
Labels: 2.0

#1064 [#466222] Grid: fixed initialization availableHeight on IE.
  src/list/views/GridView.ts
Labels: 2.0

#1065 Builfix: compact theme (empty view font-size)
  resources/styles/list.css
Labels: 2.0

#1066 Compact theme style fixes
  resources/styles/themes/main/index.js
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
Labels: 2.0

#1068 Buildfix: compact theme (padding on fields)
  resources/styles/themes/new/index.js
Labels: 2.0

#1067 [#463661][#464149] ContextEditor, Grid: fixed collapse event and maxHeight option for grid.
  resources/styles/list.css
  src/form/editors/impl/context/views/PopoutWrapperView.js
  src/list/views/CollectionView.ts
Labels: 2.0

#1069 Fix toolbar in process designer and history
  resources/styles/themes/main/styles.css
Labels: 2.0

#1063 [#457500][#466136] [#463270] Codemirorr: add icons, functionality to …
  resources/styles/codemirror.css
  src/form/editors/impl/codeEditor/Constants.js
  src/form/editors/impl/codeEditor/services/CmwCodeAssistantServices.js
  src/form/editors/impl/codeEditor/services/MappingService.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  src/form/editors/impl/codeEditor/views/FunctionTooltipView.js
  src/utils/keyCode.ts
  tests/utils/OntologyService.js
Labels: 2.0

#1073 Fix selection cell and wrap in horizontal layout
  resources/styles/form.css
  resources/styles/themes/theme.css
  src/layout/resources/horizontalLayout.css
  src/list/views/header/GridHeaderView.ts
  src/services/ThemeService.ts
Labels: 2.0

#1074 Buildfix fix navigational panel in compact custom view
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/styles.css
Labels: 2.0

#1072 [#294573] Add class for archive templates
  resources/styles/list.css
  src/list/CellViewFactory.ts
Labels: 2.0, needs work

#1070 [#464070] Notification: fixSize
  resources/styles/notifications.css
Labels: 2.0

#1076 [#467111] Another fix selection cell
  src/list/views/header/GridHeaderView.ts
Labels: 2.0

#1071 [#466950] Codemirror: replace '\n' from server
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  tests/specs/form/CodeEditorView.spec.js
  tests/utils/OntologyService.js
Labels: 2.0

#1077 Update collection view on attach
  src/list/views/CollectionView.ts
Labels: 2.0

#1079 Add focusing selected column on configuration panel opening
  resources/styles/themes/theme.css
  src/list/views/header/GridHeaderView.ts
Labels: 2.0

#1075 [#465634]Fix members in Process designer
  dist/localization/localization.de.json
  dist/localization/localization.en.json
  dist/localization/localization.ru.json
  localization/localization.n3
  localization/localization.ru.n3
  src/form/editors/MembersSplitEditorView.ts
  src/form/editors/impl/membersSplit/controller/MembersSplitController.ts
  tests/specs/form/MemberSplitEditor.spec.js
  tests/utils/memberData.js
Labels: 2.0, need tests

#1081 [#466955]Fix members quantity warning
  resources/styles/common.css
  src/form/editors/impl/membersSplit/templates/baseMembersGrid.hbs
  src/form/editors/impl/membersSplit/views/AvailableGridView.ts
  src/form/editors/impl/membersSplit/views/BaseMembersGridView.ts
  tests/specs/form/MemberSplitEditor.spec.js
  tests/utils/memberService.js
Labels: 2.0, need tests

#1083 [#466872] Fix margin on field with tooltip
  resources/styles/themes/theme.css
Labels: 2.0

#1082 [#467365] Fix icons on the ref field
  resources/styles/dropdown.css
  resources/styles/themes/theme.css
Labels: 2.0

#1086 [#466623] Delete padding on required field (compact theme)
  resources/styles/themes/main/styles.css
Labels: 2.0

#1085 [#465828] Fix correct display of personal configuration settings icon…
  resources/styles/treeEditor.css
Labels: 2.0

#1088 Buildfix renew navigation panel according to compact theme
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/index.js
Labels: 2.0

#1094 [#466840] Fix connections icons (compact theme)
  resources/styles/themes/main/styles.css
Labels: 2.0

#1091 [#467208] Fix layout of icons on form (compact theme)
  resources/styles/themes/main/styles.css
Labels: 2.0
