Repository comindware/core-ui, pull requests merged in 2019-12, with the labels that each got.

#1097 [#464958] TabLayout: added ellispsis if tabs overflow.
  resources/styles/themes/main/index.js
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/layout/resources/popup.css
  src/layout/resources/tabLayout.css
  src/layout/tabLayout/HeaderItemView.js
  src/layout/tabLayout/HeaderMenuButtonView.js
  src/layout/tabLayout/HeaderMenuPanelItemView.js
  src/layout/tabLayout/HeaderMenuPanelView.js
  src/layout/tabLayout/HeaderView.js
  src/layout/tabLayout/TabHeaderView.js
  src/layout/tabLayout/TabHeadersView.js
  src/layout/tabLayout/TabLayoutView.js
  src/layout/tabLayout/templates/tabHeader.hbs
  src/layout/tabLayout/templates/tabLayout.hbs
  tests/specs/components/TabView.spec.js
Labels: 1.13

#1092 [468091] Add filter hints for CSharp script
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.0

#1101 Buildfix: fixed split-view on scroll
  resources/styles/common.css
Labels: 2.0

#1100 [#463680]Fix operations form cursor (IE)
  src/form/editors/DatalistEditorView.ts
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.0

#1102 [#466997] Fix height of filter popup (compact theme)
  src/form/editors/BooleanGroupEditorView.ts
Labels: 2.0

#1098 [#468260] CodeEditor: add method the return compile result
  src/form/editors/CodeEditorView.ts
  src/form/editors/impl/codeEditor/templates/toolbar.html
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  src/form/editors/impl/codeEditor/views/OutputView.js
  src/form/editors/impl/codeEditor/views/ToolbarView.js
Labels: 2.0, Stas review me please

#1099 [#466652] Fix text fields on personal profile
  resources/styles/themes/main/index.js
  resources/styles/themes/main/styles.css
Labels: 2.0, needs work

#1109 [#469139] CodeEditor: exclude punctuation to filter commands C#
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1, Stas review me please

#1106 [#469198] ComplexEditor: fix set value
  src/form/editors/ComplexEditorView.js
Labels: 2.1, Stas review me please

#1104 [#468795] Fix call method intelliAssist
  src/form/editors/impl/codeEditor/services/CmwCodeAssistantServices.js
Labels: 2.1, Stas review me please

#1111 [#468345] Add comparison condition seporatorLine
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  tests/specs/form/CodeEditorView.spec.js
Labels: 2.1

#1123 [#469529]Fix non-closing dropdown on SPACE (2.0)
  src/form/editors/DatalistEditorView.ts
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.0

#1108 [#469529]Fix non-closing dropdown on SPACE
  src/form/editors/DatalistEditorView.ts
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.1

#1118 [#469445]Removed all users title (not needed)
  src/form/editors/DatalistEditorView.ts
Labels: 2.0

#1124 [#469445]Removed all users title (not needed) (2.1)
  src/form/editors/DatalistEditorView.ts
Labels: 2.1

#1119 [#469452] Fix padding of daughterly cells on collection
  resources/styles/themes/new/styles.css
Labels: 2.1

#1120 [#469452] Fix padding of daughterly cells on collection
  resources/styles/themes/new/styles.css
Labels: 2.0

#1117 add borders for drag element
  src/services/UIService.ts
Labels: 2.1

#1113 [#469473][#456033] Datalist layout: set nowrap, min-width for input, commented cell logic.
  resources/styles/form.css
Labels: 2.0

#1114 [#469473][#456033] Datalist layout: set nowrap, min-width for input, …
  resources/styles/form.css
Labels: 2.1

#1112 [#469558] Fix display collection (IE)
  resources/styles/list.css
  resources/styles/themes/theme.css
Labels: 2.0

#1115 [#469558] Fix display collection (IE)
  resources/styles/list.css
  resources/styles/themes/theme.css
Labels: 2.1

#1096 TabLayout: added ellispsis if tabs overflow (merge from 1.13).
  demo/styles/demo.css
  resources/styles/themes/main/index.js
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/dropdown/factory.ts
  src/form/editors/DatalistEditorView.ts
  src/layout/resources/popup.css
  src/layout/resources/tabLayout.css
  src/layout/tabLayout/HeaderItemView.js
  src/layout/tabLayout/HeaderItemView.ts
  src/layout/tabLayout/HeaderMenuButtonView.ts
  src/layout/tabLayout/HeaderMenuPanelItemView.ts
  src/layout/tabLayout/HeaderMenuPanelView.ts
  src/layout/tabLayout/HeaderView.js
  src/layout/tabLayout/TabHeaderView.ts
  src/layout/tabLayout/TabHeadersView.ts
  src/layout/tabLayout/TabLayoutView.ts
  src/layout/tabLayout/templates/tabHeader.hbs
  src/layout/tabLayout/templates/tabLayout.hbs
  tests/specs/components/TabView.spec.js
Labels: 2.0

#1125 TabLayout: added ellispsis if tabs overflow (merge from 1.13).
  demo/styles/demo.css
  resources/styles/themes/main/index.js
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/dropdown/factory.ts
  src/form/editors/DatalistEditorView.ts
  src/layout/resources/popup.css
  src/layout/resources/tabLayout.css
  src/layout/tabLayout/HeaderItemView.js
  src/layout/tabLayout/HeaderItemView.ts
  src/layout/tabLayout/HeaderMenuButtonView.ts
  src/layout/tabLayout/HeaderMenuPanelItemView.ts
  src/layout/tabLayout/HeaderMenuPanelView.ts
  src/layout/tabLayout/HeaderView.js
  src/layout/tabLayout/TabHeaderView.ts
  src/layout/tabLayout/TabHeadersView.ts
  src/layout/tabLayout/TabLayoutView.ts
  src/layout/tabLayout/templates/tabHeader.hbs
  src/layout/tabLayout/templates/tabLayout.hbs
  tests/specs/components/TabView.spec.js
Labels: 2.1

#1122 Tabs: switch scrollIntoView to scrollIntoViewIfNeeded.
  src/layout/tabLayout/HeaderItemView.js
Labels: 1.13

#1128 [#466644]Fix horizontal scrollbar in collection (2.0)
  resources/styles/list.css
Labels: 2.0

#1126 [#466644]Fix horizontal scrollbar in collection
  resources/styles/list.css
Labels: 2.1

#1116 [#469454]Fix right click on column header
  src/list/views/header/GridHeaderView.ts
Labels: 2.0

#1127 [#469454]Fix right click on column header and checkbox (2.1)
  src/list/views/header/GridHeaderView.ts
Labels: 2.1

#1121 [#470170] Add filter methods (call Ctrl+Space)
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1134 Grid: fixed borders collapse and sticky chrome gaps, horizontal scroll.
  resources/styles/list.css
  resources/styles/themes/main/index.js
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/index.js
  resources/styles/themes/theme.css
  src/list/views/GridView.ts
Labels: 2.1

#1133 Fix text width of document type's column filter
  resources/styles/form.css
Labels: 2.0

#1136 [#469686] Fix text width of document type's column filter
  resources/styles/form.css
Labels: 2.1

#1135 [#469452] Fix icons on daughterly cells
  resources/styles/list.css
Labels: 2.1

#1137 [#469452] Fix icons on daughterly cells
  resources/styles/list.css
Labels: 2.0

#1132 [#469595][#467983] Fix fields in settings of starting event (timer) and on system forms
  src/layout/resources/horizontalLayout.css
Labels: 2.0

#1131 [#469595][#467983] Fix fields in settings of starting event (timer) and on system forms
  src/layout/resources/horizontalLayout.css
Labels: 2.1

#1141 [#463377] Tabs: added isShow wrapper on visible and isHidden.
  src/layout/tabLayout/HeaderItemView.ts
  src/layout/tabLayout/HeaderMenuPanelItemView.ts
  src/layout/tabLayout/TabHeaderView.ts
  src/layout/tabLayout/TabLayoutView.ts
  src/layout/tabLayout/models/TabModel.ts
Labels: 2.0

#1142 [#463377] Tabs: added isShow wrapper on visible and isHidden.
  src/layout/tabLayout/HeaderItemView.ts
  src/layout/tabLayout/HeaderMenuPanelItemView.ts
  src/layout/tabLayout/TabHeaderView.ts
  src/layout/tabLayout/TabLayoutView.ts
  src/layout/tabLayout/models/TabModel.ts
Labels: 2.1

#1138 Redesign history and data configure pages
  resources/styles/themes/main/styles.css
Labels: 2.1

#1146 Buildfix: fix checkboxes for Edge
  resources/styles/themes/theme.css
Labels: 2.1

#1147 [#471360] Datalist: fixed display bubbles model change.
  resources/styles/form.css
  resources/styles/themes/theme.css
  src/form/editors/ComplexEditorView.js
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/meta.ts
  src/form/editors/impl/datalist/views/BubbleCollectionView.ts
Labels: 2.1
