Repository comindware/core-ui, pull requests merged in 2020-03, with the labels that each got.

#1227 [#476640] CodeEditor: fix hidden hints
  src/form/editors/impl/codeEditor/Constants.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1230 Added generate changelog md task.
  CHANGELOG.md
  build/gulpfile.js
  build/tasks/generateChangeLogTask.js
  build/tasks/prepareToPublishTask.js
Labels: 2.1

#1210 [#476313] Datalist: Prevented trigger blur event on panel click.
  src/form/editors/DatalistEditorView.ts
Labels: 2.1, need tests

#1233 Buildfix - change the condition for N3
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1232 Buildfix: turned off dropdown reopen test
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.1

#1240 ButtonView: Fallback to name for title was added.
  src/components/toolbar/views/ButtonView.js
Labels: 2.1

#1239 ButtonView: Fallback to name for title was added.
  src/components/toolbar/views/ButtonView.js
Labels: 2.0

#1243 IEService: addition of Number.isNaN polyfill.
  src/services/IEService.ts
Labels: 2.1

#1229 Add option icon for datalist
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/views/ReferenceListWithSubtextItemView.js
Labels: 2.0

#1228 Add option icon for datalist
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/views/ReferenceListWithSubtextItemView.js
Labels: 2.1

#1235 Added Role type to objectPropertyTypes.
  src/Meta.ts
Labels: 2.1

#1244 [#478634] Add icons for Enum and OS
  src/Meta.ts
Labels: 2.1

#1245 [#478911] Fix highlighting N3
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1242 [#478934] Fix display data on integrations
  src/form/editors/DatalistEditorView.ts
  src/list/CellViewFactory.ts
  src/utils/helpers.ts
Labels: 2.1

#1249 [#478913] Fix text highlighting for CMW
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1248 Bugfix - add a type 'OrganizationUnit'
  src/Meta.ts
  src/form/editors/ComplexEditorView.js
  src/form/editors/ContextSelectEditorView.js
Labels: 2.1

#1254 DurationEditor: fixation of hours per day option.
  demo/app/cases/editors/DurationEditor.js
  src/form/editors/DurationEditorView.js
  src/list/CellViewFactory.ts
Labels: 2.1

#1252 EdgeService: fixation of insertAdjacentHTML polyfill.
  src/services/EdgeService.ts
Labels: 2.1

#1253 [#464436]Fix membersSplit filter
  src/form/editors/impl/membersSplit/controller/MembersSplitController.ts
Labels: 2.1

#1258 [#479015] [#479780] VirtualCollection: fix visible collection
  src/collections/VirtualCollection.ts
Labels: 2.1

#1257 [#473692]Fix roles display in global substitutions
  src/form/editors/MembersSplitEditorView.ts
Labels: 2.1

#1260 GridView: fixation of validate (return undefined if array is empty).
  src/list/views/GridView.ts
Labels: 2.1

#1261 Bugfix - fix check array
  src/form/editors/impl/codeEditor/services/CmwCodeAssistantServices.js
Labels: 2.1

#1265 [#479896] Fix validation for grid
  src/list/views/GridView.ts
Labels: 2.1

#1264 Grid optimization
  demo/public/app/cases/components/PopupViewLayoutForm.js
  demo/public/app/cases/list/complexGrid.js
  demo/public/app/cases/list/editableGrid.js
  demo/public/app/cases/list/gridSearchAndSelection.js
  resources/styles/codemirror.css
  resources/styles/form.css
  resources/styles/list.css
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/Meta.ts
  src/collections/VirtualCollection.js
  src/dropdown/views/DropdownView.js
  src/form/editors/CodeEditorView.js
  src/form/editors/ComplexEditorView.js
  src/form/editors/ContextSelectEditorView.js
  src/form/editors/DatalistEditorView.js
  src/form/editors/base/MarionetteEditorPrototype.js
  src/form/editors/impl/codeEditor/templates/codeEditor.html
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  src/form/editors/templates/durationEditor.hbs
  src/form/editors/templates/numberEditor.hbs
  src/form/editors/templates/passwordEditor.hbs
  src/form/editors/templates/textEditor.hbs
  src/form/fields/SimplifiedFieldView.js
  src/form/fields/views/SimplifiedButtonView.js
  src/form/fields/views/SimplifiedPanelView.js
  src/form/formRepository.js
  src/layout/tabLayout/TabLayoutView.js
  src/layout/tabLayout/templates/tabLayout.hbs
  src/list/CellViewFactory.js
  src/list/CellViewFactory.ts
  src/list/behaviors/GridItemBehavior.ts
  src/list/meta.ts
  src/list/templates/compositeDocumentCell.html
  src/list/templates/compositeReferenceCell.html
  src/list/templates/compositeUserCell.html
  src/list/templates/selectionCell.hbs
  src/list/types/types.ts
  src/list/views/CellFieldView.js
  src/list/views/CollectionView.js
  src/list/views/GridView.js
  src/list/views/RowView.js
  src/list/views/header/GridHeaderView.js
  src/list/views/selections/SelectionCellView.js
  src/list/views/selections/SelectionPanelView.js
  src/services/GlobalEventService.js
  src/services/WindowService.js
  src/services/window/views/PopupStackView.js
  tests/specs/form/ComplexEditor.spec.js
  tests/specs/form/DatalistEditorView.spec.js
  tests/specs/form/DateTimeEditorView.spec.js
  tests/specs/form/MemberSplitEditor.spec.js
Labels: 1.13

#1268 [#479793] Fix button contrast
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/form/editors/templates/documentEditor.html
Labels: 2.1

#1266 [#479793] Fix button contrast
  resources/styles/themes/new/styles.css
Labels: 2.0

#1263 [#480644] Add icon for attribute
  src/form/editors/impl/codeEditor/services/CmwCodeAssistantServices.js
Labels: 2.1

#1262 [#479838] Fix to skip change input editor
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1267 [#476633] Set init width on columns (personal/system config)
  src/components/treeEditor/controllers/DiffController.ts
  src/list/views/GridView.ts
  src/list/views/header/GridHeaderView.ts
Labels: 2.1

#1270 [#475806] Fix remove icon on search input
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
Labels: 2.0

#1272 [#479280]Fix session monitoring activities field
  src/list/CellViewFactory.ts
  src/list/views/RowView.ts
Labels: 2.1

#1273 [#476633] Set init width on columns (personal/system config) v2.0
  src/components/treeEditor/controllers/DiffController.ts
  src/list/views/GridView.ts
  src/list/views/header/GridHeaderView.ts
Labels: 2.0

#1274 [#468345] CodeEditor: fix line separator (3.5)
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.0

#1275 [#479922] GridView: draggable apply only for sequencial checked rows.
  resources/styles/list.css
  resources/styles/themes/theme.css
  src/list/behaviors/GridItemBehavior.ts
  src/list/templates/draggableDots.html
  src/list/views/CollectionView.ts
  src/list/views/GridView.ts
  src/list/views/RowView.ts
  src/list/views/header/GridHeaderView.ts
  src/models/behaviors/CheckableBehavior.ts
Labels: 2.1

#1269 [#479922] GridView: draggable apply only for sequencial checked rows.
  resources/styles/list.css
  src/form/editors/base/MarionetteEditorPrototype.ts
  src/list/behaviors/GridCollapsibleItemBehavior.ts
  src/list/views/CollectionView.ts
  src/list/views/GridView.ts
  src/list/views/RowView.ts
  src/list/views/header/GridHeaderView.ts
  src/models/behaviors/CheckableBehavior.ts
Labels: 2.0

#1279 Datalist: fixation of navigate to links.
  src/form/editors/DatalistEditorView.ts
Labels: 2.1

#1278 [#470606] Fix display composite count with a long section name
  resources/styles/list.css
Labels: 2.1
