Repository comindware/core-ui, pull requests merged in 2020-01, with the labels that each got.

#1150 Buildfix: added CSS linter (Core UI)
  .stylelintrc.json
  build/webpack.config.js
  package-lock.json
  package.json
  resources/styles/blink-checkbox.css
  resources/styles/codemirror.css
  resources/styles/common.css
  resources/styles/date-picker.css
  resources/styles/dropdown.css
  resources/styles/fonts.css
  resources/styles/form.css
  resources/styles/gallery.css
  resources/styles/icon-editor.css
  resources/styles/list.css
  resources/styles/notifications.css
  resources/styles/pastel-on-dark.css
  resources/styles/popout.css
  resources/styles/services/messageService.css
  resources/styles/services/windowService.css
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  resources/styles/treeEditor.css
  vc-config.code-workspace
Labels: 2.1

#1154 IEService: added once addEventListener option polyfill.
  src/services/IEService.ts
Labels: 2.1

#1162 Buildfix: fix member split editor issues
  src/form/editors/MembersSplitEditorView.ts
  src/form/editors/impl/membersSplit/controller/MembersSplitController.ts
  tests/specs/form/MemberSplitEditor.spec.js
Labels: 2.1

#1161 [#473155] CodeEditor: separation of hints for expression-cmw and n3
  src/form/editors/impl/codeEditor/Constants.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1158 [#472252] CMW-Expression: do not call a point request
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1157 Buildfix: checkbox background
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
Labels: 2.1

#1156 [#458571] Add event keydown Shift+Enter
  src/list/views/CollectionView.ts
Labels: 2.1

#1153 [#469729]Fix creating new records without addNew button
  src/form/editors/DatalistEditorView.ts
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.1

#1164 Grid: fixed header first-child left border on hover.
  resources/styles/themes/theme.css
Labels: 2.1

#1169 Grid: fixed getHidden option.
  src/list/views/RowView.ts
Labels: 2.1

#1170 DateTime localization: removed kludge for timezone offsets.
  src/services/LocalizationService.ts
Labels: 2.1

#1173 DateHelpers: transfer dateTime format names to CoreUI.
  src/utils/dateHelpers.ts
Labels: 2.1

#1174 Add compact search's version for mobile&tablet
  resources/styles/themes/main/index.js
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/views/SearchBarView.ts
  src/views/templates/searchBar.hbs
Labels: 2.0

#1159 Compact: transfer history panel compact to product.
  resources/styles/themes/main/styles.css
  src/utils/handlebars/getIconUnicode.ts
Labels: 2.1, question

#1177 Buildfix: removed duplicate click from datalist
  src/form/editors/DatalistEditorView.ts
Labels: 2.1

#1176 Small grid and datalist optimization
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/views/BubbleItemView.ts
  src/list/CellViewFactory.ts
  src/list/views/RowView.ts
Labels: 2.1

#1180 Multivalue cells optimization
  src/list/CellViewFactory.ts
  src/list/views/GridView.ts
Labels: 2.1

#1181 2.1/small magor fixes
  src/form/editors/ComplexEditorView.js
  src/form/editors/DatalistEditorView.ts
  src/layout/form/FormSchemaFactory.ts
Labels: 2.1

#1182 Datalist: added selected data pass to collections fetch.
  src/form/editors/DatalistEditorView.ts
Labels: 2.1

#1172 [#474121][#473586][#474141][#474166]CodeEditor: add the list attributes for 'object:fi…
  src/form/editors/impl/codeEditor/Constants.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
  src/form/editors/impl/codeEditor/views/ToolbarView.js
Labels: 2.1

#1179 Buildfix: fix memberSplit issues
  src/form/editors/MembersSplitEditorView.js
  src/form/editors/impl/membersSplit/controller/MembersSplitController.js
  tests/specs/form/MemberSplitEditor.spec.js
  tests/utils/memberService.js
Labels: 1.13

#1165 Add compact search's version for mobile&tablet and fix navbar
  resources/styles/themes/main/index.js
  resources/styles/themes/main/styles.css
  resources/styles/themes/new/index.js
  resources/styles/themes/new/styles.css
  resources/styles/themes/theme.css
  src/list/views/GridView.ts
  src/services/ThemeService.ts
  src/views/SearchBarView.ts
  src/views/templates/searchBar.hbs
Labels: 2.1, needs work

#1185 Fix grid's search
  src/list/views/GridView.ts
  src/views/SearchBarView.ts
Labels: 2.1

#1184 Buildfix: fix test bug in DatalistTest
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.1
