Repository comindware/core-ui, pull requests merged in 2020-02, with the labels that each got.

#1191 Fix 'icon remove' style and color
  resources/styles/themes/new/index.js
  resources/styles/themes/theme.css
  src/form/editors/iconsWraps/iconWrapRemove.html
  src/form/editors/iconsWraps/iconWrapRemoveBubble.html
  src/form/editors/impl/codeEditor/templates/codeEditor.html
  src/form/editors/impl/iconEditor/templates/iconEditorComponentView.html
  src/form/editors/templates/avatarEditor.hbs
  src/form/editors/templates/colorPicker.hbs
  src/form/editors/templates/contextSelectEditor.html
  src/form/editors/templates/timeEditor.hbs
  src/views/templates/searchBar.hbs
Labels: 2.1

#1188 Fix listeners error
  src/services/ThemeService.ts
Labels: 2.1

#1187 Buildfix: optimized icons
  src/Meta.ts
  src/form/editors/impl/iconEditor/icons.json
Labels: 2.1

#1192 [#473395] Fix checkbox with index
  resources/styles/themes/theme.css
Labels: 2.1

#1197 [#473037] Fix default tabs
  src/layout/resources/tabLayout.css
Labels: 2.1

#1199 [#472998] GreadHeader: fix width the first column without check-box
  src/list/views/header/GridHeaderView.ts
Labels: 2.1

#1200 [#472998] GreadHeader: fix width the first column without check-box
  src/list/views/header/GridHeaderView.ts
Labels: 2.0

#1201 [#473037] Fix default tabs
  src/layout/resources/tabLayout.css
Labels: 2.0

#1202 [#474981] GridView: event split for Enter key
  src/list/views/CollectionView.ts
Labels: 2.0

#1198 Fix filter on enter key
  src/form/editors/DatalistEditorView.ts
  src/form/editors/DateTimeEditorView.ts
Labels: 2.0

#1196 [#474829] Fix bubbles form on collection
  resources/styles/form.css
Labels: 2.0

#1195 [#474829] Fix bubbles form on collection
  resources/styles/form.css
Labels: 2.1

#1205 [#471360][#462891] Datalist cherry-picks from 2.1.
  src/form/editors/DatalistEditorView.ts
  src/form/editors/impl/datalist/collections/DemoReferenceCollection.js
  src/form/editors/impl/datalist/views/ButtonView.ts
  src/form/fields/FieldView.ts
  tests/specs/form/DatalistEditorView.spec.js
Labels: 2.0

#1204 Datalist: fixed recursive fetch data for absent ids.
  src/form/editors/DatalistEditorView.ts
Labels: 2.1

#1207 Fix filter on enter key
  src/form/editors/DatalistEditorView.ts
  src/form/editors/DateTimeEditorView.ts
Labels: 2.1

#1208 [#473402] Set init position columns (personal/system config)
  src/components/treeEditor/TreeEditor.ts
  src/components/treeEditor/controllers/DiffController.ts
  src/list/views/GridView.ts
Labels: 2.0

#1209 [#476313] Datalist: Prevented trigger blur event on panel click.
  src/form/editors/DatalistEditorView.ts
Labels: 2.0

#1211 [#473402] Set init position columns (personal/system config)
  src/components/treeEditor/TreeEditor.ts
  src/components/treeEditor/controllers/DiffController.ts
  src/list/views/GridView.ts
Labels: 2.1

#1212 [#476407] Fix border on collection
  resources/styles/list.css
  resources/styles/themes/theme.css
Labels: 2.0

#1213 [#476683] Add solution for ComplexEditor
  src/form/editors/ComplexEditorView.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1

#1217 2.1/update packages
  .eslintrc.js
  babel.config.json
  build/gulpfile.js
  build/webpack.config.js
  package-lock.json
  package.json
  src/form/editors/impl/radioGroup/collections/RadioGroupCollection.js
  src/layout/button/ButtonView.js
  src/layout/split/SplitPanel.js
  src/layout/tabLayout/StepperItemView.js
  src/layout/tabLayout/StepperView.js
  vc-config.code-workspace
Labels: 2.1

#1216 Update npm packages.
  package-lock.json
  package.json
Labels: 2.0

#1221 Fix validation
  src/form/editors/base/MarionetteEditorPrototype.ts
Labels: 2.1

#1222 Fix 'dataTimeEditor' filter's focus and filter's value delay
  src/form/editors/DatalistEditorView.ts
  src/form/editors/DateTimeEditorView.ts
  src/form/editors/base/MarionetteEditorPrototype.ts
Labels: 2.0

#1215 Fix 'dataTimeEditor' filter's focus and filter's value delay
  src/form/editors/DatalistEditorView.ts
  src/form/editors/DateTimeEditorView.ts
  src/form/editors/base/MarionetteEditorPrototype.ts
Labels: 2.1, need tests

#1214 [#476407] Fix border on collection
  resources/styles/themes/theme.css
Labels: 2.0

#1223 [#477617] CodeEditor: change language when usins ctr+v or left mause…
  src/form/editors/impl/codeEditor/Constants.js
  src/form/editors/impl/codeEditor/views/CodemirrorView.js
Labels: 2.1
